// Deterministic JSON → LaTeX using Jake Gutierrez's resume template
// (https://github.com/jakegut/resume, MIT License, based on sb2nov/resume).
// Same resume JSON in → byte-identical .tex out.

const PREAMBLE = String.raw`%-------------------------
% Resume in Latex
% Author : Jake Gutierrez
% Based off of: https://github.com/sb2nov/resume
% License : MIT
% Generated by JobPilot from resume JSON -- edit the JSON, not this file.
%------------------------

\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}

\pagestyle{fancy}
\fancyhf{} % clear all header and footer fields
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% Adjust margins
\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}

\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

% Sections formatting
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

% Ensure that generate pdf is machine readable/ATS parsable
% (pdfTeX only; skipped on XeTeX/Tectonic, which emit Unicode anyway)
\ifdefined\pdfgentounicode
  \input{glyphtounicode}
  \pdfgentounicode=1
\fi

%-------------------------
% Custom commands
\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubSubheading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \textit{\small#1} & \textit{\small #2} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}

\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}
`;

// Characters pdflatex (with the template's default encoding) handles.
const UNICODE_MAP = {
  "–": "--",
  "—": "---",
  "‘": "`",
  "’": "'",
  "“": "``",
  "”": "''",
  "…": "\\ldots{}",
  "•": "\\textbullet{}",
  "→": "$\\rightarrow$",
  "←": "$\\leftarrow$",
  "≥": "$\\geq$",
  "≤": "$\\leq$",
  "×": "$\\times$",
  "±": "$\\pm$",
  "°": "$^\\circ$",
  "€": "EUR",
  "£": "\\pounds{}",
  " ": "~",
};

const ASCII_MAP = {
  "\\": "\\textbackslash{}",
  "&": "\\&",
  "%": "\\%",
  $: "\\$",
  "#": "\\#",
  _: "\\_",
  "{": "\\{",
  "}": "\\}",
  "~": "$\\sim$",
  "^": "\\textasciicircum{}",
  "<": "\\textless{}",
  ">": "\\textgreater{}",
  "|": "$|$",
};

// Escape plain text for LaTeX. Letters with accents (é, ñ, ü…) pass through
// (LaTeX reads UTF-8); unsupported symbols such as emoji are dropped.
export function escapeTex(text) {
  let out = "";
  for (const ch of String(text ?? "").normalize("NFC")) {
    if (ASCII_MAP[ch] !== undefined) out += ASCII_MAP[ch];
    else if (UNICODE_MAP[ch] !== undefined) out += UNICODE_MAP[ch];
    else if (/[\x20-\x7e]/.test(ch)) out += ch;
    else if (/[À-ſ]/.test(ch)) out += ch;
    else if (/\s/.test(ch)) out += " ";
    // anything else (emoji, CJK, symbols) is dropped
  }
  return out.replace(/ {2,}/g, " ").trim();
}

// URLs inside \href{...}: only these need escaping.
function escapeUrl(url) {
  return String(url || "").replace(/\\/g, "/").replace(/([%#{}])/g, "\\$1").replace(/\s/g, "%20");
}

const displayUrl = (u) => String(u || "").replace(/^https?:\/\//, "").replace(/^www\./, "").replace(/\/$/, "");
const fullUrl = (u) => (/^(https?:|mailto:)/.test(u) ? u : `https://${u}`);
const visible = (arr) => (arr || []).filter((x) => !x.hidden);

function sectionStyle(title) {
  const t = (title || "").toLowerCase();
  if (/project/.test(t)) return "project";
  if (/experience|employment|work|leadership|activities|involvement|research/.test(t)) return "experience";
  return "education";
}

function header(b) {
  const parts = [];
  if (b.phone) parts.push(escapeTex(b.phone));
  if (b.email) parts.push(`\\href{mailto:${escapeUrl(b.email)}}{\\underline{${escapeTex(b.email)}}}`);
  if (b.location) parts.push(escapeTex(b.location));
  for (const l of b.links || []) {
    if (!l.url) continue;
    parts.push(`\\href{${escapeUrl(fullUrl(l.url))}}{\\underline{${escapeTex(displayUrl(l.url))}}}`);
  }
  const lines = ["\\begin{center}", `    \\textbf{\\Huge \\scshape ${escapeTex(b.name)}} \\\\ \\vspace{1pt}`];
  if (parts.length) lines.push(`    \\small ${parts.join(" $|$ \n    ")}`);
  lines.push("\\end{center}");
  return lines.join("\n");
}

function bullets(list, indent) {
  const items = visible(list).filter((b) => (b.text || "").trim());
  if (!items.length) return [];
  return [`${indent}\\resumeItemListStart`, ...items.map((b) => `${indent}  \\resumeItem{${escapeTex(b.text)}}`), `${indent}\\resumeItemListEnd`];
}

function entriesSection(s) {
  const style = sectionStyle(s.title);
  const out = ["  \\resumeSubHeadingListStart"];
  for (const e of visible(s.entries)) {
    const dates = escapeTex(e.dates);
    if (style === "project") {
      const name = `\\textbf{${escapeTex(e.title)}}${e.subtitle ? ` $|$ \\emph{${escapeTex(e.subtitle)}}` : ""}`;
      out.push("    \\resumeProjectHeading", `        {${name}}{${dates}}`);
    } else if (style === "experience") {
      // Jake's experience layout: role (bold) / dates, then organization (italic) / location.
      const role = e.subtitle || e.title;
      const org = e.subtitle ? e.title : "";
      out.push("    \\resumeSubheading", `      {${escapeTex(role)}}{${dates}}`, `      {${escapeTex(org)}}{${escapeTex(e.location)}}`);
    } else {
      out.push("    \\resumeSubheading", `      {${escapeTex(e.title)}}{${escapeTex(e.location)}}`, `      {${escapeTex(e.subtitle)}}{${dates}}`);
    }
    out.push(...bullets(e.bullets, "      "));
  }
  out.push("  \\resumeSubHeadingListEnd");
  return out;
}

function linesSection(s) {
  const rows = visible(s.lines).filter((l) => l.label || l.text);
  const body = rows.map((l) => (l.label ? `     \\textbf{${escapeTex(l.label)}}{: ${escapeTex(l.text)}}` : `     ${escapeTex(l.text)}`)).join(" \\\\\n");
  return [" \\begin{itemize}[leftmargin=0.15in, label={}]", "    \\small{\\item{", body, "    }}", " \\end{itemize}"];
}

function textSection(s) {
  return [" \\begin{itemize}[leftmargin=0.15in, label={}]", `    \\small{\\item{${escapeTex(s.text)}}}`, " \\end{itemize}"];
}

export function resumeToLatex(resume) {
  const r = resume || {};
  const out = [PREAMBLE, "", "\\begin{document}", "", header(r.basics || {})];
  if ((r.summary || "").trim()) {
    out.push("", "\\section{Summary}", ...textSection({ text: r.summary }));
  }
  for (const s of r.sections || []) {
    const hasContent = s.kind === "entries" ? visible(s.entries).length : s.kind === "lines" ? visible(s.lines).some((l) => l.label || l.text) : (s.text || "").trim();
    if (!hasContent) continue;
    out.push("", `%-----------${escapeTex(s.title).toUpperCase()}-----------`, `\\section{${escapeTex(s.title)}}`);
    if (s.kind === "entries") out.push(...entriesSection(s));
    else if (s.kind === "lines") out.push(...linesSection(s));
    else out.push(...textSection(s));
  }
  out.push("", "\\end{document}", "");
  return out.join("\n");
}
