// Deterministic JSON → LaTeX in the style of Jake Gutierrez's resume
// template (https://github.com/jakegut/resume, MIT License, based on
// sb2nov/resume). Same resume JSON and scale in → byte-identical .tex out.
//
// Layout comes from layout.js (shared with the built-in renderer): every
// line is its own paragraph with a fixed leading, and the vertical gaps are
// explicit, so positions match pdf.js and scale together to fit one page.
import { METRICS as M, entryLines, richRuns, contactItems, sectionLayout } from "./layout.js";

const LEAD = 11; // leading of every line; other gaps are added with \vspace

// Characters pdflatex (with the template's default encoding) handles.
const UNICODE_MAP = {
  "–": "--",
  "—": "---",
  "‘": "`",
  "’": "'",
  "“": "``",
  "”": "''",
  "…": "\\ldots{}",
  "•": "\\textbullet{}",
  "→": "$\\rightarrow$",
  "←": "$\\leftarrow$",
  "≥": "$\\geq$",
  "≤": "$\\leq$",
  "×": "$\\times$",
  "±": "$\\pm$",
  "°": "$^\\circ$",
  "€": "EUR",
  "£": "\\pounds{}",
  " ": "~",
};

const ASCII_MAP = {
  "\\": "\\textbackslash{}",
  "&": "\\&",
  "%": "\\%",
  $: "\\$",
  "#": "\\#",
  _: "\\_",
  "{": "\\{",
  "}": "\\}",
  "~": "$\\sim$",
  "^": "\\textasciicircum{}",
  "<": "\\textless{}",
  ">": "\\textgreater{}",
  "|": "$|$",
};

// Escape plain text for LaTeX. Letters with accents (é, ñ, ü…) pass through
// (LaTeX reads UTF-8); unsupported symbols such as emoji are dropped.
export function escapeTex(text) {
  let out = "";
  for (const ch of String(text ?? "").normalize("NFC")) {
    if (ASCII_MAP[ch] !== undefined) out += ASCII_MAP[ch];
    else if (UNICODE_MAP[ch] !== undefined) out += UNICODE_MAP[ch];
    else if (/[\x20-\x7e]/.test(ch)) out += ch;
    else if (/[À-ſ]/.test(ch)) out += ch;
    else if (/\s/.test(ch)) out += " ";
    // anything else (emoji, CJK, symbols) is dropped
  }
  return out.replace(/ {2,}/g, " ").trim();
}

// URLs inside \href{...}: only these need escaping.
function escapeUrl(url) {
  return String(url || "").replace(/\\/g, "/").replace(/([%#{}])/g, "\\$1").replace(/\s/g, "%20");
}

const visible = (arr) => (arr || []).filter((x) => !x.hidden);
// Lengths in bp (PDF points, 1/72in) to match layout.js; TeX's pt is 1/72.27in.
const n = (x) => `${Math.round(x * 100) / 100}bp`;
// Font sizes stay in TeX points, like the template's own 9pt/10pt fonts.
const fs = (x) => `${Math.round(x * 100) / 100}`;

function runTex(r) {
  // escapeTex trims; keep the spaces between runs.
  let t = `${/^\s/.test(r.t) ? " " : ""}${escapeTex(r.t)}${/\s$/.test(r.t) ? " " : ""}`;
  if (r.style === "bold") t = `\\textbf{${t}}`;
  else if (r.style === "italic") t = `\\textit{${t}}`;
  else if (r.style === "bolditalic") t = `\\textbf{\\textit{${t}}}`;
  if (r.u) t = `\\underline{${t}}`;
  if (r.url) t = `\\href{${escapeUrl(r.url)}}{${t}}`;
  return t;
}
const runsTex = (runs) => runs.map(runTex).join("");

function preamble(k, side = M.page.side) {
  const P = { ...M.page, side };
  const rowW = M.rowWidth * (P.w - 2 * P.side);
  return String.raw`%-------------------------
% Resume in LaTeX, in the style of Jake Gutierrez's template
% (https://github.com/jakegut/resume, MIT License, based on sb2nov/resume).
% Generated by JobPilot from resume JSON -- edit the JSON, not this file.
%-------------------------

\RequirePackage{fix-cm} % scalable Computer Modern, so sizes can shrink to fit
\documentclass[letterpaper,10pt]{article}
\usepackage[letterpaper,left=${n(P.side)},right=${n(P.side)},top=${n(P.top)},bottom=${n(P.bottom)}]{geometry}
\usepackage[hidelinks]{hyperref}
\urlstyle{same}
\pagestyle{empty}
\raggedright
\setlength{\parindent}{0pt}
\setlength{\parskip}{0pt}
\setlength{\topskip}{${n(27.2 * k)}}
\setlength{\lineskiplimit}{-100pt} % always use the exact leading

% Ensure that generated PDF is machine readable/ATS parsable
% (pdfTeX only; skipped on XeTeX/Tectonic, which emit Unicode anyway)
\ifdefined\pdfgentounicode
  \input{glyphtounicode}
  \pdfgentounicode=1
\fi

\newcommand{\sz}[1]{\fontsize{#1}{${n(LEAD * k)}}\selectfont}
\newlength{\rowW}\setlength{\rowW}{${n(rowW)}}

% A heading row: left text, right text flush with the right edge. Long left
% text wraps instead of running into the right side.
\newcommand{\row}[2]{%
  \setbox1\hbox{#1}\setbox2\hbox{#2}%
  \noindent\hspace*{${n(M.indent)}}%
  \ifdim\dimexpr\wd1+\wd2+8pt\relax>\rowW
    \parbox[t]{\dimexpr\rowW-\wd2-8pt\relax}{\raggedright #1}\hspace{8pt}\box2%
  \else
    \makebox[\rowW][l]{\box1\hfill\box2}%
  \fi\par}

\newcommand{\bulletitem}[1]{{\leftskip=${n(M.bulletTextX)}\noindent\llap{\makebox[${n(M.bulletTextX - M.bulletX)}][l]{\raisebox{${n(1.3 * k)}}{$\scriptscriptstyle\bullet$}}}#1\par}}

\newcommand{\sectiontitle}[1]{\noindent\rlap{\rule[${n(-M.gap.ruleBelowTitle * k)}]{\textwidth}{0.4pt}}{\scshape #1}\par}
`;
}

export function resumeToLatex(resume, scale = 1) {
  const k = scale;
  const S = M.size;
  const G = M.gap;
  const r = resume || {};
  const b = r.basics || {};
  const out = [preamble(k), "\\begin{document}", ""];
  let first = true;
  // Baseline-to-baseline gap before the next line.
  const gap = (g) => {
    if (first) return (first = false);
    const extra = (g - LEAD) * k;
    if (Math.abs(extra) > 0.005) out.push(`\\vspace{${n(extra)}}`);
  };
  const size = (s) => `\\sz{${fs(s * k)}}`;

  if (b.name) {
    gap(0);
    out.push(`{\\centering ${size(S.name)}\\textbf{${escapeTex(b.name)}}\\par}`);
  }
  const contact = contactItems(b).map((c) => runTex({ t: c.t, style: "normal", u: !!c.url, url: c.url }));
  if (contact.length) {
    gap(G.nameToContact);
    out.push(`{\\centering ${size(S.contact)}${contact.join(" $|$ ")}\\par}`);
  }

  // What the previous line was, to pick the right gap.
  let prev = "contact";
  const toSection = () => (prev === "contact" ? G.contactToSection : prev === "line" ? G.linesToSection : G.toSection);

  const bulletsTex = (bullets) => {
    const items = visible(bullets).filter((x) => (x.text || "").trim());
    items.forEach((x, i) => {
      gap(i === 0 ? G.headingToBullet : G.bullet);
      out.push(`${size(S.bullet)}\\bulletitem{${runsTex(richRuns(x.text))}}`);
    });
    if (items.length) prev = "bullet";
  };

  const section = (title, firstGap) => {
    gap(toSection());
    out.push("", `%----------- ${escapeTex(title).toUpperCase()} -----------`, `${size(S.section)}\\sectiontitle{${escapeTex(title)}}`);
    prev = "title";
    return firstGap;
  };

  if ((r.summary || "").trim()) {
    section("Summary");
    gap(G.sectionToLines);
    out.push(`${size(S.text)}\\noindent\\hspace*{${n(M.indent)}}${runsTex(richRuns(r.summary))}\\par`);
    prev = "line";
  }

  for (const s of r.sections || []) {
    const entries = visible(s.entries);
    const lines = visible(s.lines).filter((l) => l.label || l.text);
    const has = s.kind === "entries" ? entries.length : s.kind === "lines" ? lines.length : (s.text || "").trim();
    if (!has) continue;
    section(s.title || "");

    if (s.kind === "entries") {
      const { layout } = sectionLayout(s);
      entries.forEach((e) => {
        for (const line of entryLines(s, e)) {
          if (line.kind === "bottom") gap(G.topToBottom);
          else if (prev === "title") gap(layout === "inline" ? G.sectionToInline : layout === "row" ? G.sectionToRow : G.sectionToHeading);
          else if (prev === "row") gap(G.afterRowToRow);
          else gap(layout === "inline" ? G.afterBulletsToInline : G.afterBulletsToHeading);
          const ls = { top: S.top, bottom: S.bottom, inline: S.inline, row: S.row }[line.kind];
          const rs = { top: S.topRight, bottom: S.bottom, inline: S.inlineRight, row: S.row }[line.kind];
          const right = line.right.length ? `${size(rs)}${runsTex(line.right)}` : "";
          out.push(`${size(ls)}\\row{${runsTex(line.left)}}{${right}}`);
          prev = line.kind === "row" ? "row" : "heading";
        }
        bulletsTex(e.bullets);
      });
    } else {
      const items = s.kind === "lines" ? lines : [{ label: "", text: s.text }];
      items.forEach((l, i) => {
        gap(i === 0 ? G.sectionToLines : G.line);
        const label = l.label ? `\\textbf{${escapeTex(l.label)}}: ` : "";
        out.push(`${size(S.line)}{\\leftskip=${n(M.indent)}\\noindent ${label}${runsTex(richRuns(l.text))}\\par}`);
      });
      prev = "line";
    }
  }
  out.push("", "\\end{document}", "");
  return out.join("\n");
}

// Cover letter: the resume's header and fonts, letter-width margins.
export const LETTER = { side: 54, size: 10, lead: 13, gap: 8, headerGap: 24 };

export function coverToLatex(basics, letter, dateText) {
  const b = basics || {};
  const k = 1;
  const out = [preamble(k, LETTER.side), "\\begin{document}", ""];
  if (b.name) out.push(`{\\centering \\sz{${fs(M.size.name)}}\\textbf{${escapeTex(b.name)}}\\par}`);
  const contact = contactItems(b).map((c) => runTex({ t: c.t, style: "normal", u: !!c.url, url: c.url }));
  if (contact.length) out.push(`\\vspace{${n(M.gap.nameToContact - LEAD)}}`, `{\\centering \\sz{${fs(M.size.contact)}}${contact.join(" $|$ ")}\\par}`);
  const para = (t) => `{\\fontsize{${fs(LETTER.size)}}{${n(LETTER.lead)}}\\selectfont ${escapeTex(t)}\\par}`;
  out.push(`\\vspace{${n(LETTER.headerGap)}}`, para(dateText || ""), `\\vspace{${n(LETTER.gap)}}`, para(letter.greeting));
  for (const p of letter.paragraphs) out.push(`\\vspace{${n(LETTER.gap)}}`, para(p));
  out.push(`\\vspace{${n(LETTER.gap)}}`, para(letter.signoff), para(b.name || ""), "", "\\end{document}", "");
  return out.join("\n");
}
